// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: proto/auth/auth-endpoint.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - auth.AuthEndpoint

/// Namespace containing generated types for the "auth.AuthEndpoint" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Auth_AuthEndpoint: Sendable {
    /// Service descriptor for the "auth.AuthEndpoint" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "auth.AuthEndpoint")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "SignIn" metadata.
        public enum SignIn: Sendable {
            /// Request type for "SignIn".
            public typealias Input = Auth_SignInRequest
            /// Response type for "SignIn".
            public typealias Output = Auth_SignInResponse
            /// Descriptor for "SignIn".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "auth.AuthEndpoint"),
                method: "SignIn",
                type: .unary
            )
        }
        /// Namespace for "SignUp" metadata.
        public enum SignUp: Sendable {
            /// Request type for "SignUp".
            public typealias Input = Auth_SignUpRequest
            /// Response type for "SignUp".
            public typealias Output = Auth_SignUpResponse
            /// Descriptor for "SignUp".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "auth.AuthEndpoint"),
                method: "SignUp",
                type: .unary
            )
        }
        /// Namespace for "SignOut" metadata.
        public enum SignOut: Sendable {
            /// Request type for "SignOut".
            public typealias Input = Auth_SignOutRequest
            /// Response type for "SignOut".
            public typealias Output = Auth_SignOutResponse
            /// Descriptor for "SignOut".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "auth.AuthEndpoint"),
                method: "SignOut",
                type: .unary
            )
        }
        /// Namespace for "RefreshTokens" metadata.
        public enum RefreshTokens: Sendable {
            /// Request type for "RefreshTokens".
            public typealias Input = Auth_RefreshTokensRequest
            /// Response type for "RefreshTokens".
            public typealias Output = Auth_RefreshTokensResponse
            /// Descriptor for "RefreshTokens".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "auth.AuthEndpoint"),
                method: "RefreshTokens",
                type: .unary
            )
        }
        /// Descriptors for all methods in the "auth.AuthEndpoint" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            SignIn.descriptor,
            SignUp.descriptor,
            SignOut.descriptor,
            RefreshTokens.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "auth.AuthEndpoint" service.
    public static let auth_AuthEndpoint = GRPCCore.ServiceDescriptor(fullyQualifiedService: "auth.AuthEndpoint")
}

// MARK: auth.AuthEndpoint (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Auth_AuthEndpoint {
    /// Generated client protocol for the "auth.AuthEndpoint" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "SignIn" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > SignIn авторизация пользователя по логину и паролю
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Auth_SignInRequest` message.
        ///   - serializer: A serializer for `Auth_SignInRequest` messages.
        ///   - deserializer: A deserializer for `Auth_SignInResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func signIn<Result>(
            request: GRPCCore.ClientRequest<Auth_SignInRequest>,
            serializer: some GRPCCore.MessageSerializer<Auth_SignInRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Auth_SignInResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Auth_SignInResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "SignUp" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > SignUp регистрация пользователя
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Auth_SignUpRequest` message.
        ///   - serializer: A serializer for `Auth_SignUpRequest` messages.
        ///   - deserializer: A deserializer for `Auth_SignUpResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func signUp<Result>(
            request: GRPCCore.ClientRequest<Auth_SignUpRequest>,
            serializer: some GRPCCore.MessageSerializer<Auth_SignUpRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Auth_SignUpResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Auth_SignUpResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "SignOut" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > SignOut выход пользователя из приложения
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Auth_SignOutRequest` message.
        ///   - serializer: A serializer for `Auth_SignOutRequest` messages.
        ///   - deserializer: A deserializer for `Auth_SignOutResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func signOut<Result>(
            request: GRPCCore.ClientRequest<Auth_SignOutRequest>,
            serializer: some GRPCCore.MessageSerializer<Auth_SignOutRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Auth_SignOutResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Auth_SignOutResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "RefreshTokens" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > RefreshTokens обновление токенов
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Auth_RefreshTokensRequest` message.
        ///   - serializer: A serializer for `Auth_RefreshTokensRequest` messages.
        ///   - deserializer: A deserializer for `Auth_RefreshTokensResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func refreshTokens<Result>(
            request: GRPCCore.ClientRequest<Auth_RefreshTokensRequest>,
            serializer: some GRPCCore.MessageSerializer<Auth_RefreshTokensRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Auth_RefreshTokensResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Auth_RefreshTokensResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "auth.AuthEndpoint" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "SignIn" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > SignIn авторизация пользователя по логину и паролю
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Auth_SignInRequest` message.
        ///   - serializer: A serializer for `Auth_SignInRequest` messages.
        ///   - deserializer: A deserializer for `Auth_SignInResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func signIn<Result>(
            request: GRPCCore.ClientRequest<Auth_SignInRequest>,
            serializer: some GRPCCore.MessageSerializer<Auth_SignInRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Auth_SignInResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Auth_SignInResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Auth_AuthEndpoint.Method.SignIn.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "SignUp" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > SignUp регистрация пользователя
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Auth_SignUpRequest` message.
        ///   - serializer: A serializer for `Auth_SignUpRequest` messages.
        ///   - deserializer: A deserializer for `Auth_SignUpResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func signUp<Result>(
            request: GRPCCore.ClientRequest<Auth_SignUpRequest>,
            serializer: some GRPCCore.MessageSerializer<Auth_SignUpRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Auth_SignUpResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Auth_SignUpResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Auth_AuthEndpoint.Method.SignUp.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "SignOut" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > SignOut выход пользователя из приложения
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Auth_SignOutRequest` message.
        ///   - serializer: A serializer for `Auth_SignOutRequest` messages.
        ///   - deserializer: A deserializer for `Auth_SignOutResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func signOut<Result>(
            request: GRPCCore.ClientRequest<Auth_SignOutRequest>,
            serializer: some GRPCCore.MessageSerializer<Auth_SignOutRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Auth_SignOutResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Auth_SignOutResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Auth_AuthEndpoint.Method.SignOut.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "RefreshTokens" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > RefreshTokens обновление токенов
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Auth_RefreshTokensRequest` message.
        ///   - serializer: A serializer for `Auth_RefreshTokensRequest` messages.
        ///   - deserializer: A deserializer for `Auth_RefreshTokensResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func refreshTokens<Result>(
            request: GRPCCore.ClientRequest<Auth_RefreshTokensRequest>,
            serializer: some GRPCCore.MessageSerializer<Auth_RefreshTokensRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Auth_RefreshTokensResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Auth_RefreshTokensResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Auth_AuthEndpoint.Method.RefreshTokens.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Auth_AuthEndpoint.ClientProtocol {
    /// Call the "SignIn" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > SignIn авторизация пользователя по логину и паролю
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Auth_SignInRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func signIn<Result>(
        request: GRPCCore.ClientRequest<Auth_SignInRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Auth_SignInResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.signIn(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Auth_SignInRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Auth_SignInResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SignUp" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > SignUp регистрация пользователя
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Auth_SignUpRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func signUp<Result>(
        request: GRPCCore.ClientRequest<Auth_SignUpRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Auth_SignUpResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.signUp(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Auth_SignUpRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Auth_SignUpResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SignOut" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > SignOut выход пользователя из приложения
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Auth_SignOutRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func signOut<Result>(
        request: GRPCCore.ClientRequest<Auth_SignOutRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Auth_SignOutResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.signOut(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Auth_SignOutRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Auth_SignOutResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "RefreshTokens" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > RefreshTokens обновление токенов
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Auth_RefreshTokensRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func refreshTokens<Result>(
        request: GRPCCore.ClientRequest<Auth_RefreshTokensRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Auth_RefreshTokensResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.refreshTokens(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Auth_RefreshTokensRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Auth_RefreshTokensResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Auth_AuthEndpoint.ClientProtocol {
    /// Call the "SignIn" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > SignIn авторизация пользователя по логину и паролю
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func signIn<Result>(
        _ message: Auth_SignInRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Auth_SignInResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Auth_SignInRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.signIn(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SignUp" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > SignUp регистрация пользователя
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func signUp<Result>(
        _ message: Auth_SignUpRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Auth_SignUpResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Auth_SignUpRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.signUp(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SignOut" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > SignOut выход пользователя из приложения
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func signOut<Result>(
        _ message: Auth_SignOutRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Auth_SignOutResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Auth_SignOutRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.signOut(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "RefreshTokens" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > RefreshTokens обновление токенов
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func refreshTokens<Result>(
        _ message: Auth_RefreshTokensRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Auth_RefreshTokensResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Auth_RefreshTokensRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.refreshTokens(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}