// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: proto/auditLog/auditLog-endpoint.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - auditLog.AuditLogEndpoint

/// Namespace containing generated types for the "auditLog.AuditLogEndpoint" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum AuditLog_AuditLogEndpoint: Sendable {
    /// Service descriptor for the "auditLog.AuditLogEndpoint" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "auditLog.AuditLogEndpoint")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "GetAuditLogs" metadata.
        public enum GetAuditLogs: Sendable {
            /// Request type for "GetAuditLogs".
            public typealias Input = AuditLog_GetAuditLogsRequest
            /// Response type for "GetAuditLogs".
            public typealias Output = AuditLog_GetAuditLogsResponse
            /// Descriptor for "GetAuditLogs".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "auditLog.AuditLogEndpoint"),
                method: "GetAuditLogs",
                type: .unary
            )
        }
        /// Descriptors for all methods in the "auditLog.AuditLogEndpoint" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            GetAuditLogs.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "auditLog.AuditLogEndpoint" service.
    public static let auditLog_AuditLogEndpoint = GRPCCore.ServiceDescriptor(fullyQualifiedService: "auditLog.AuditLogEndpoint")
}

// MARK: auditLog.AuditLogEndpoint (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension AuditLog_AuditLogEndpoint {
    /// Generated client protocol for the "auditLog.AuditLogEndpoint" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "GetAuditLogs" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > GetAuditLogs получение записей аудит-лога, доступных пользователю по группам счетов
        ///
        /// - Parameters:
        ///   - request: A request containing a single `AuditLog_GetAuditLogsRequest` message.
        ///   - serializer: A serializer for `AuditLog_GetAuditLogsRequest` messages.
        ///   - deserializer: A deserializer for `AuditLog_GetAuditLogsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getAuditLogs<Result>(
            request: GRPCCore.ClientRequest<AuditLog_GetAuditLogsRequest>,
            serializer: some GRPCCore.MessageSerializer<AuditLog_GetAuditLogsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<AuditLog_GetAuditLogsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<AuditLog_GetAuditLogsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "auditLog.AuditLogEndpoint" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "GetAuditLogs" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > GetAuditLogs получение записей аудит-лога, доступных пользователю по группам счетов
        ///
        /// - Parameters:
        ///   - request: A request containing a single `AuditLog_GetAuditLogsRequest` message.
        ///   - serializer: A serializer for `AuditLog_GetAuditLogsRequest` messages.
        ///   - deserializer: A deserializer for `AuditLog_GetAuditLogsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getAuditLogs<Result>(
            request: GRPCCore.ClientRequest<AuditLog_GetAuditLogsRequest>,
            serializer: some GRPCCore.MessageSerializer<AuditLog_GetAuditLogsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<AuditLog_GetAuditLogsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<AuditLog_GetAuditLogsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: AuditLog_AuditLogEndpoint.Method.GetAuditLogs.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension AuditLog_AuditLogEndpoint.ClientProtocol {
    /// Call the "GetAuditLogs" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > GetAuditLogs получение записей аудит-лога, доступных пользователю по группам счетов
    ///
    /// - Parameters:
    ///   - request: A request containing a single `AuditLog_GetAuditLogsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getAuditLogs<Result>(
        request: GRPCCore.ClientRequest<AuditLog_GetAuditLogsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<AuditLog_GetAuditLogsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getAuditLogs(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<AuditLog_GetAuditLogsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<AuditLog_GetAuditLogsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension AuditLog_AuditLogEndpoint.ClientProtocol {
    /// Call the "GetAuditLogs" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > GetAuditLogs получение записей аудит-лога, доступных пользователю по группам счетов
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getAuditLogs<Result>(
        _ message: AuditLog_GetAuditLogsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<AuditLog_GetAuditLogsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<AuditLog_GetAuditLogsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getAuditLogs(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}