// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: proto/auditLog/auditLog-endpoint.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum AuditLog_AuditLogEntity: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0

  /// Транзакция
  case transaction // = 1

  /// Счет
  case account // = 2

  /// Группа счетов
  case accountGroup // = 3

  /// Подкатегория
  case tag // = 4

  /// Пользователь
  case user // = 5

  /// Валюта
  case currency // = 6
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .transaction
    case 2: self = .account
    case 3: self = .accountGroup
    case 4: self = .tag
    case 5: self = .user
    case 6: self = .currency
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .transaction: return 1
    case .account: return 2
    case .accountGroup: return 3
    case .tag: return 4
    case .user: return 5
    case .currency: return 6
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [AuditLog_AuditLogEntity] = [
    .unspecified,
    .transaction,
    .account,
    .accountGroup,
    .tag,
    .user,
    .currency,
  ]

}

public enum AuditLog_AuditLogMethod: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case methodUnspecified // = 0

  /// Создание
  case create // = 1

  /// Обновление
  case update // = 2

  /// Удаление
  case delete // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .methodUnspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .methodUnspecified
    case 1: self = .create
    case 2: self = .update
    case 3: self = .delete
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .methodUnspecified: return 0
    case .create: return 1
    case .update: return 2
    case .delete: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [AuditLog_AuditLogMethod] = [
    .methodUnspecified,
    .create,
    .update,
    .delete,
  ]

}

public struct AuditLog_AuditLog: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Числовой идентификатор записи
  public var id: UInt32 = 0

  /// Название сущности
  public var entity: AuditLog_AuditLogEntity = .unspecified

  /// Метод изменения
  public var method: AuditLog_AuditLogMethod = .methodUnspecified

  /// Идентификатор сущности (без FK)
  public var entityID: String = String()

  /// Слепок сущности до изменения в формате JSON
  public var snapshotBefore: Data {
    get {return _snapshotBefore ?? Data()}
    set {_snapshotBefore = newValue}
  }
  /// Returns true if `snapshotBefore` has been explicitly set.
  public var hasSnapshotBefore: Bool {return self._snapshotBefore != nil}
  /// Clears the value of `snapshotBefore`. Subsequent reads from it will return its default value.
  public mutating func clearSnapshotBefore() {self._snapshotBefore = nil}

  /// Слепок сущности после изменения в формате JSON
  public var snapshotAfter: Data {
    get {return _snapshotAfter ?? Data()}
    set {_snapshotAfter = newValue}
  }
  /// Returns true if `snapshotAfter` has been explicitly set.
  public var hasSnapshotAfter: Bool {return self._snapshotAfter != nil}
  /// Clears the value of `snapshotAfter`. Subsequent reads from it will return its default value.
  public mutating func clearSnapshotAfter() {self._snapshotAfter = nil}

  /// Идентификатор пользователя, совершившего действие
  public var userID: Data = Data()

  /// Идентификатор устройства, с которого совершено действие
  public var deviceID: String = String()

  /// Идентификатор группы счетов (отсутствует для глобальных сущностей)
  public var accountGroupID: Data {
    get {return _accountGroupID ?? Data()}
    set {_accountGroupID = newValue}
  }
  /// Returns true if `accountGroupID` has been explicitly set.
  public var hasAccountGroupID: Bool {return self._accountGroupID != nil}
  /// Clears the value of `accountGroupID`. Subsequent reads from it will return its default value.
  public mutating func clearAccountGroupID() {self._accountGroupID = nil}

  /// Дата и время изменения
  public var datetimeCreate: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _datetimeCreate ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_datetimeCreate = newValue}
  }
  /// Returns true if `datetimeCreate` has been explicitly set.
  public var hasDatetimeCreate: Bool {return self._datetimeCreate != nil}
  /// Clears the value of `datetimeCreate`. Subsequent reads from it will return its default value.
  public mutating func clearDatetimeCreate() {self._datetimeCreate = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _snapshotBefore: Data? = nil
  fileprivate var _snapshotAfter: Data? = nil
  fileprivate var _accountGroupID: Data? = nil
  fileprivate var _datetimeCreate: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

public struct AuditLog_GetAuditLogsRequest: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Токен доступа
  public var accessToken: String = String()

  /// Фильтр по группе счетов (должна быть доступна пользователю)
  public var accountGroupID: Data {
    get {return _accountGroupID ?? Data()}
    set {_accountGroupID = newValue}
  }
  /// Returns true if `accountGroupID` has been explicitly set.
  public var hasAccountGroupID: Bool {return self._accountGroupID != nil}
  /// Clears the value of `accountGroupID`. Subsequent reads from it will return its default value.
  public mutating func clearAccountGroupID() {self._accountGroupID = nil}

  /// Фильтр по названию сущности
  public var entity: AuditLog_AuditLogEntity {
    get {return _entity ?? .unspecified}
    set {_entity = newValue}
  }
  /// Returns true if `entity` has been explicitly set.
  public var hasEntity: Bool {return self._entity != nil}
  /// Clears the value of `entity`. Subsequent reads from it will return its default value.
  public mutating func clearEntity() {self._entity = nil}

  /// Фильтр по методу изменения
  public var method: AuditLog_AuditLogMethod {
    get {return _method ?? .methodUnspecified}
    set {_method = newValue}
  }
  /// Returns true if `method` has been explicitly set.
  public var hasMethod: Bool {return self._method != nil}
  /// Clears the value of `method`. Subsequent reads from it will return its default value.
  public mutating func clearMethod() {self._method = nil}

  /// Фильтр по идентификатору сущности
  public var entityID: String {
    get {return _entityID ?? String()}
    set {_entityID = newValue}
  }
  /// Returns true if `entityID` has been explicitly set.
  public var hasEntityID: Bool {return self._entityID != nil}
  /// Clears the value of `entityID`. Subsequent reads from it will return its default value.
  public mutating func clearEntityID() {self._entityID = nil}

  /// Ограничение количества записей
  public var limit: UInt32 {
    get {return _limit ?? 0}
    set {_limit = newValue}
  }
  /// Returns true if `limit` has been explicitly set.
  public var hasLimit: Bool {return self._limit != nil}
  /// Clears the value of `limit`. Subsequent reads from it will return its default value.
  public mutating func clearLimit() {self._limit = nil}

  /// Смещение выборки
  public var offset: UInt32 {
    get {return _offset ?? 0}
    set {_offset = newValue}
  }
  /// Returns true if `offset` has been explicitly set.
  public var hasOffset: Bool {return self._offset != nil}
  /// Clears the value of `offset`. Subsequent reads from it will return its default value.
  public mutating func clearOffset() {self._offset = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _accountGroupID: Data? = nil
  fileprivate var _entity: AuditLog_AuditLogEntity? = nil
  fileprivate var _method: AuditLog_AuditLogMethod? = nil
  fileprivate var _entityID: String? = nil
  fileprivate var _limit: UInt32? = nil
  fileprivate var _offset: UInt32? = nil
}

public struct AuditLog_GetAuditLogsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Объект ошибки
  public var error: Error_Error {
    get {return _error ?? Error_Error()}
    set {_error = newValue}
  }
  /// Returns true if `error` has been explicitly set.
  public var hasError: Bool {return self._error != nil}
  /// Clears the value of `error`. Subsequent reads from it will return its default value.
  public mutating func clearError() {self._error = nil}

  /// Список записей аудит-лога
  public var auditLogs: [AuditLog_AuditLog] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _error: Error_Error? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "auditLog"

extension AuditLog_AuditLogEntity: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "Unspecified"),
    1: .same(proto: "Transaction"),
    2: .same(proto: "Account"),
    3: .same(proto: "AccountGroup"),
    4: .same(proto: "Tag"),
    5: .same(proto: "User"),
    6: .same(proto: "Currency"),
  ]
}

extension AuditLog_AuditLogMethod: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "MethodUnspecified"),
    1: .same(proto: "Create"),
    2: .same(proto: "Update"),
    3: .same(proto: "Delete"),
  ]
}

extension AuditLog_AuditLog: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AuditLog"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "entity"),
    3: .same(proto: "method"),
    4: .same(proto: "entityID"),
    5: .same(proto: "snapshotBefore"),
    6: .same(proto: "snapshotAfter"),
    7: .same(proto: "userID"),
    8: .same(proto: "deviceID"),
    9: .same(proto: "accountGroupID"),
    10: .same(proto: "datetimeCreate"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.id) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.entity) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.method) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.entityID) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self._snapshotBefore) }()
      case 6: try { try decoder.decodeSingularBytesField(value: &self._snapshotAfter) }()
      case 7: try { try decoder.decodeSingularBytesField(value: &self.userID) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 9: try { try decoder.decodeSingularBytesField(value: &self._accountGroupID) }()
      case 10: try { try decoder.decodeSingularMessageField(value: &self._datetimeCreate) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.id != 0 {
      try visitor.visitSingularUInt32Field(value: self.id, fieldNumber: 1)
    }
    if self.entity != .unspecified {
      try visitor.visitSingularEnumField(value: self.entity, fieldNumber: 2)
    }
    if self.method != .methodUnspecified {
      try visitor.visitSingularEnumField(value: self.method, fieldNumber: 3)
    }
    if !self.entityID.isEmpty {
      try visitor.visitSingularStringField(value: self.entityID, fieldNumber: 4)
    }
    try { if let v = self._snapshotBefore {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._snapshotAfter {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 6)
    } }()
    if !self.userID.isEmpty {
      try visitor.visitSingularBytesField(value: self.userID, fieldNumber: 7)
    }
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 8)
    }
    try { if let v = self._accountGroupID {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 9)
    } }()
    try { if let v = self._datetimeCreate {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: AuditLog_AuditLog, rhs: AuditLog_AuditLog) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.entity != rhs.entity {return false}
    if lhs.method != rhs.method {return false}
    if lhs.entityID != rhs.entityID {return false}
    if lhs._snapshotBefore != rhs._snapshotBefore {return false}
    if lhs._snapshotAfter != rhs._snapshotAfter {return false}
    if lhs.userID != rhs.userID {return false}
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs._accountGroupID != rhs._accountGroupID {return false}
    if lhs._datetimeCreate != rhs._datetimeCreate {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension AuditLog_GetAuditLogsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetAuditLogsRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "accessToken"),
    2: .same(proto: "accountGroupID"),
    3: .same(proto: "entity"),
    4: .same(proto: "method"),
    5: .same(proto: "entityID"),
    6: .same(proto: "limit"),
    7: .same(proto: "offset"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.accessToken) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self._accountGroupID) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self._entity) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self._method) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._entityID) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self._limit) }()
      case 7: try { try decoder.decodeSingularUInt32Field(value: &self._offset) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.accessToken.isEmpty {
      try visitor.visitSingularStringField(value: self.accessToken, fieldNumber: 1)
    }
    try { if let v = self._accountGroupID {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._entity {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._method {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._entityID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._limit {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._offset {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 7)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: AuditLog_GetAuditLogsRequest, rhs: AuditLog_GetAuditLogsRequest) -> Bool {
    if lhs.accessToken != rhs.accessToken {return false}
    if lhs._accountGroupID != rhs._accountGroupID {return false}
    if lhs._entity != rhs._entity {return false}
    if lhs._method != rhs._method {return false}
    if lhs._entityID != rhs._entityID {return false}
    if lhs._limit != rhs._limit {return false}
    if lhs._offset != rhs._offset {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension AuditLog_GetAuditLogsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetAuditLogsResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "error"),
    2: .same(proto: "auditLogs"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._error) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.auditLogs) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._error {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.auditLogs.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.auditLogs, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: AuditLog_GetAuditLogsResponse, rhs: AuditLog_GetAuditLogsResponse) -> Bool {
    if lhs._error != rhs._error {return false}
    if lhs.auditLogs != rhs.auditLogs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
