// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: proto/transaction/transaction-endpoint.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - transaction.TransactionEndpoint

/// Namespace containing generated types for the "transaction.TransactionEndpoint" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
internal enum Transaction_TransactionEndpoint {
    /// Service descriptor for the "transaction.TransactionEndpoint" service.
    internal static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "transaction.TransactionEndpoint")
    /// Namespace for method metadata.
    internal enum Method {
        /// Namespace for "GetTransactions" metadata.
        internal enum GetTransactions {
            /// Request type for "GetTransactions".
            internal typealias Input = Transaction_GetTransactionsRequest
            /// Response type for "GetTransactions".
            internal typealias Output = Transaction_GetTransactionsResponse
            /// Descriptor for "GetTransactions".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "transaction.TransactionEndpoint"),
                method: "GetTransactions"
            )
        }
        /// Namespace for "CreateTransaction" metadata.
        internal enum CreateTransaction {
            /// Request type for "CreateTransaction".
            internal typealias Input = Transaction_CreateTransactionRequest
            /// Response type for "CreateTransaction".
            internal typealias Output = Transaction_CreateTransactionResponse
            /// Descriptor for "CreateTransaction".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "transaction.TransactionEndpoint"),
                method: "CreateTransaction"
            )
        }
        /// Namespace for "UpdateTransaction" metadata.
        internal enum UpdateTransaction {
            /// Request type for "UpdateTransaction".
            internal typealias Input = Transaction_UpdateTransactionRequest
            /// Response type for "UpdateTransaction".
            internal typealias Output = Transaction_UpdateTransactionResponse
            /// Descriptor for "UpdateTransaction".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "transaction.TransactionEndpoint"),
                method: "UpdateTransaction"
            )
        }
        /// Namespace for "DeleteTransaction" metadata.
        internal enum DeleteTransaction {
            /// Request type for "DeleteTransaction".
            internal typealias Input = Transaction_DeleteTransactionRequest
            /// Response type for "DeleteTransaction".
            internal typealias Output = Transaction_DeleteTransactionResponse
            /// Descriptor for "DeleteTransaction".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "transaction.TransactionEndpoint"),
                method: "DeleteTransaction"
            )
        }
        /// Descriptors for all methods in the "transaction.TransactionEndpoint" service.
        internal static let descriptors: [GRPCCore.MethodDescriptor] = [
            GetTransactions.descriptor,
            CreateTransaction.descriptor,
            UpdateTransaction.descriptor,
            DeleteTransaction.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "transaction.TransactionEndpoint" service.
    internal static let transaction_TransactionEndpoint = GRPCCore.ServiceDescriptor(fullyQualifiedService: "transaction.TransactionEndpoint")
}

// MARK: transaction.TransactionEndpoint (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Transaction_TransactionEndpoint {
    /// Streaming variant of the service protocol for the "transaction.TransactionEndpoint" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    internal protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "GetTransactions" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > GetTransactions получение всех транзакций
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Transaction_GetTransactionsRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Transaction_GetTransactionsResponse` messages.
        func getTransactions(
            request: GRPCCore.StreamingServerRequest<Transaction_GetTransactionsRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Transaction_GetTransactionsResponse>

        /// Handle the "CreateTransaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > CreateTransaction создание транзакции
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Transaction_CreateTransactionRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Transaction_CreateTransactionResponse` messages.
        func createTransaction(
            request: GRPCCore.StreamingServerRequest<Transaction_CreateTransactionRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Transaction_CreateTransactionResponse>

        /// Handle the "UpdateTransaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > UpdateTransaction редактирование транзакции
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Transaction_UpdateTransactionRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Transaction_UpdateTransactionResponse` messages.
        func updateTransaction(
            request: GRPCCore.StreamingServerRequest<Transaction_UpdateTransactionRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Transaction_UpdateTransactionResponse>

        /// Handle the "DeleteTransaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > DeleteTransaction удаление транзакции
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Transaction_DeleteTransactionRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Transaction_DeleteTransactionResponse` messages.
        func deleteTransaction(
            request: GRPCCore.StreamingServerRequest<Transaction_DeleteTransactionRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Transaction_DeleteTransactionResponse>
    }

    /// Service protocol for the "transaction.TransactionEndpoint" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    internal protocol ServiceProtocol: Transaction_TransactionEndpoint.StreamingServiceProtocol {
        /// Handle the "GetTransactions" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > GetTransactions получение всех транзакций
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Transaction_GetTransactionsRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Transaction_GetTransactionsResponse` message.
        func getTransactions(
            request: GRPCCore.ServerRequest<Transaction_GetTransactionsRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Transaction_GetTransactionsResponse>

        /// Handle the "CreateTransaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > CreateTransaction создание транзакции
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Transaction_CreateTransactionRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Transaction_CreateTransactionResponse` message.
        func createTransaction(
            request: GRPCCore.ServerRequest<Transaction_CreateTransactionRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Transaction_CreateTransactionResponse>

        /// Handle the "UpdateTransaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > UpdateTransaction редактирование транзакции
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Transaction_UpdateTransactionRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Transaction_UpdateTransactionResponse` message.
        func updateTransaction(
            request: GRPCCore.ServerRequest<Transaction_UpdateTransactionRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Transaction_UpdateTransactionResponse>

        /// Handle the "DeleteTransaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > DeleteTransaction удаление транзакции
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Transaction_DeleteTransactionRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Transaction_DeleteTransactionResponse` message.
        func deleteTransaction(
            request: GRPCCore.ServerRequest<Transaction_DeleteTransactionRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Transaction_DeleteTransactionResponse>
    }

    /// Simple service protocol for the "transaction.TransactionEndpoint" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    internal protocol SimpleServiceProtocol: Transaction_TransactionEndpoint.ServiceProtocol {
        /// Handle the "GetTransactions" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > GetTransactions получение всех транзакций
        ///
        /// - Parameters:
        ///   - request: A `Transaction_GetTransactionsRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Transaction_GetTransactionsResponse` to respond with.
        func getTransactions(
            request: Transaction_GetTransactionsRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Transaction_GetTransactionsResponse

        /// Handle the "CreateTransaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > CreateTransaction создание транзакции
        ///
        /// - Parameters:
        ///   - request: A `Transaction_CreateTransactionRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Transaction_CreateTransactionResponse` to respond with.
        func createTransaction(
            request: Transaction_CreateTransactionRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Transaction_CreateTransactionResponse

        /// Handle the "UpdateTransaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > UpdateTransaction редактирование транзакции
        ///
        /// - Parameters:
        ///   - request: A `Transaction_UpdateTransactionRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Transaction_UpdateTransactionResponse` to respond with.
        func updateTransaction(
            request: Transaction_UpdateTransactionRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Transaction_UpdateTransactionResponse

        /// Handle the "DeleteTransaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > DeleteTransaction удаление транзакции
        ///
        /// - Parameters:
        ///   - request: A `Transaction_DeleteTransactionRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Transaction_DeleteTransactionResponse` to respond with.
        func deleteTransaction(
            request: Transaction_DeleteTransactionRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Transaction_DeleteTransactionResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Transaction_TransactionEndpoint.StreamingServiceProtocol {
    internal func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Transaction_TransactionEndpoint.Method.GetTransactions.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Transaction_GetTransactionsRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Transaction_GetTransactionsResponse>(),
            handler: { request, context in
                try await self.getTransactions(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Transaction_TransactionEndpoint.Method.CreateTransaction.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Transaction_CreateTransactionRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Transaction_CreateTransactionResponse>(),
            handler: { request, context in
                try await self.createTransaction(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Transaction_TransactionEndpoint.Method.UpdateTransaction.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Transaction_UpdateTransactionRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Transaction_UpdateTransactionResponse>(),
            handler: { request, context in
                try await self.updateTransaction(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Transaction_TransactionEndpoint.Method.DeleteTransaction.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Transaction_DeleteTransactionRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Transaction_DeleteTransactionResponse>(),
            handler: { request, context in
                try await self.deleteTransaction(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Transaction_TransactionEndpoint.ServiceProtocol {
    internal func getTransactions(
        request: GRPCCore.StreamingServerRequest<Transaction_GetTransactionsRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Transaction_GetTransactionsResponse> {
        let response = try await self.getTransactions(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    internal func createTransaction(
        request: GRPCCore.StreamingServerRequest<Transaction_CreateTransactionRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Transaction_CreateTransactionResponse> {
        let response = try await self.createTransaction(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    internal func updateTransaction(
        request: GRPCCore.StreamingServerRequest<Transaction_UpdateTransactionRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Transaction_UpdateTransactionResponse> {
        let response = try await self.updateTransaction(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    internal func deleteTransaction(
        request: GRPCCore.StreamingServerRequest<Transaction_DeleteTransactionRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Transaction_DeleteTransactionResponse> {
        let response = try await self.deleteTransaction(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Transaction_TransactionEndpoint.SimpleServiceProtocol {
    internal func getTransactions(
        request: GRPCCore.ServerRequest<Transaction_GetTransactionsRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Transaction_GetTransactionsResponse> {
        return GRPCCore.ServerResponse<Transaction_GetTransactionsResponse>(
            message: try await self.getTransactions(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    internal func createTransaction(
        request: GRPCCore.ServerRequest<Transaction_CreateTransactionRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Transaction_CreateTransactionResponse> {
        return GRPCCore.ServerResponse<Transaction_CreateTransactionResponse>(
            message: try await self.createTransaction(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    internal func updateTransaction(
        request: GRPCCore.ServerRequest<Transaction_UpdateTransactionRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Transaction_UpdateTransactionResponse> {
        return GRPCCore.ServerResponse<Transaction_UpdateTransactionResponse>(
            message: try await self.updateTransaction(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    internal func deleteTransaction(
        request: GRPCCore.ServerRequest<Transaction_DeleteTransactionRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Transaction_DeleteTransactionResponse> {
        return GRPCCore.ServerResponse<Transaction_DeleteTransactionResponse>(
            message: try await self.deleteTransaction(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: transaction.TransactionEndpoint (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Transaction_TransactionEndpoint {
    /// Generated client protocol for the "transaction.TransactionEndpoint" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    internal protocol ClientProtocol: Sendable {
        /// Call the "GetTransactions" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > GetTransactions получение всех транзакций
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Transaction_GetTransactionsRequest` message.
        ///   - serializer: A serializer for `Transaction_GetTransactionsRequest` messages.
        ///   - deserializer: A deserializer for `Transaction_GetTransactionsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getTransactions<Result>(
            request: GRPCCore.ClientRequest<Transaction_GetTransactionsRequest>,
            serializer: some GRPCCore.MessageSerializer<Transaction_GetTransactionsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Transaction_GetTransactionsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Transaction_GetTransactionsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "CreateTransaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > CreateTransaction создание транзакции
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Transaction_CreateTransactionRequest` message.
        ///   - serializer: A serializer for `Transaction_CreateTransactionRequest` messages.
        ///   - deserializer: A deserializer for `Transaction_CreateTransactionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func createTransaction<Result>(
            request: GRPCCore.ClientRequest<Transaction_CreateTransactionRequest>,
            serializer: some GRPCCore.MessageSerializer<Transaction_CreateTransactionRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Transaction_CreateTransactionResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Transaction_CreateTransactionResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "UpdateTransaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > UpdateTransaction редактирование транзакции
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Transaction_UpdateTransactionRequest` message.
        ///   - serializer: A serializer for `Transaction_UpdateTransactionRequest` messages.
        ///   - deserializer: A deserializer for `Transaction_UpdateTransactionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func updateTransaction<Result>(
            request: GRPCCore.ClientRequest<Transaction_UpdateTransactionRequest>,
            serializer: some GRPCCore.MessageSerializer<Transaction_UpdateTransactionRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Transaction_UpdateTransactionResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Transaction_UpdateTransactionResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "DeleteTransaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > DeleteTransaction удаление транзакции
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Transaction_DeleteTransactionRequest` message.
        ///   - serializer: A serializer for `Transaction_DeleteTransactionRequest` messages.
        ///   - deserializer: A deserializer for `Transaction_DeleteTransactionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func deleteTransaction<Result>(
            request: GRPCCore.ClientRequest<Transaction_DeleteTransactionRequest>,
            serializer: some GRPCCore.MessageSerializer<Transaction_DeleteTransactionRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Transaction_DeleteTransactionResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Transaction_DeleteTransactionResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "transaction.TransactionEndpoint" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    internal struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        internal init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "GetTransactions" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > GetTransactions получение всех транзакций
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Transaction_GetTransactionsRequest` message.
        ///   - serializer: A serializer for `Transaction_GetTransactionsRequest` messages.
        ///   - deserializer: A deserializer for `Transaction_GetTransactionsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func getTransactions<Result>(
            request: GRPCCore.ClientRequest<Transaction_GetTransactionsRequest>,
            serializer: some GRPCCore.MessageSerializer<Transaction_GetTransactionsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Transaction_GetTransactionsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Transaction_GetTransactionsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Transaction_TransactionEndpoint.Method.GetTransactions.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "CreateTransaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > CreateTransaction создание транзакции
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Transaction_CreateTransactionRequest` message.
        ///   - serializer: A serializer for `Transaction_CreateTransactionRequest` messages.
        ///   - deserializer: A deserializer for `Transaction_CreateTransactionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func createTransaction<Result>(
            request: GRPCCore.ClientRequest<Transaction_CreateTransactionRequest>,
            serializer: some GRPCCore.MessageSerializer<Transaction_CreateTransactionRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Transaction_CreateTransactionResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Transaction_CreateTransactionResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Transaction_TransactionEndpoint.Method.CreateTransaction.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "UpdateTransaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > UpdateTransaction редактирование транзакции
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Transaction_UpdateTransactionRequest` message.
        ///   - serializer: A serializer for `Transaction_UpdateTransactionRequest` messages.
        ///   - deserializer: A deserializer for `Transaction_UpdateTransactionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func updateTransaction<Result>(
            request: GRPCCore.ClientRequest<Transaction_UpdateTransactionRequest>,
            serializer: some GRPCCore.MessageSerializer<Transaction_UpdateTransactionRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Transaction_UpdateTransactionResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Transaction_UpdateTransactionResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Transaction_TransactionEndpoint.Method.UpdateTransaction.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "DeleteTransaction" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > DeleteTransaction удаление транзакции
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Transaction_DeleteTransactionRequest` message.
        ///   - serializer: A serializer for `Transaction_DeleteTransactionRequest` messages.
        ///   - deserializer: A deserializer for `Transaction_DeleteTransactionResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func deleteTransaction<Result>(
            request: GRPCCore.ClientRequest<Transaction_DeleteTransactionRequest>,
            serializer: some GRPCCore.MessageSerializer<Transaction_DeleteTransactionRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Transaction_DeleteTransactionResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Transaction_DeleteTransactionResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Transaction_TransactionEndpoint.Method.DeleteTransaction.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Transaction_TransactionEndpoint.ClientProtocol {
    /// Call the "GetTransactions" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > GetTransactions получение всех транзакций
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Transaction_GetTransactionsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func getTransactions<Result>(
        request: GRPCCore.ClientRequest<Transaction_GetTransactionsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Transaction_GetTransactionsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getTransactions(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Transaction_GetTransactionsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Transaction_GetTransactionsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CreateTransaction" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > CreateTransaction создание транзакции
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Transaction_CreateTransactionRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func createTransaction<Result>(
        request: GRPCCore.ClientRequest<Transaction_CreateTransactionRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Transaction_CreateTransactionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.createTransaction(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Transaction_CreateTransactionRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Transaction_CreateTransactionResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdateTransaction" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > UpdateTransaction редактирование транзакции
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Transaction_UpdateTransactionRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func updateTransaction<Result>(
        request: GRPCCore.ClientRequest<Transaction_UpdateTransactionRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Transaction_UpdateTransactionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.updateTransaction(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Transaction_UpdateTransactionRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Transaction_UpdateTransactionResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "DeleteTransaction" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > DeleteTransaction удаление транзакции
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Transaction_DeleteTransactionRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func deleteTransaction<Result>(
        request: GRPCCore.ClientRequest<Transaction_DeleteTransactionRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Transaction_DeleteTransactionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.deleteTransaction(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Transaction_DeleteTransactionRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Transaction_DeleteTransactionResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Transaction_TransactionEndpoint.ClientProtocol {
    /// Call the "GetTransactions" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > GetTransactions получение всех транзакций
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func getTransactions<Result>(
        _ message: Transaction_GetTransactionsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Transaction_GetTransactionsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Transaction_GetTransactionsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getTransactions(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CreateTransaction" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > CreateTransaction создание транзакции
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func createTransaction<Result>(
        _ message: Transaction_CreateTransactionRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Transaction_CreateTransactionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Transaction_CreateTransactionRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.createTransaction(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdateTransaction" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > UpdateTransaction редактирование транзакции
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func updateTransaction<Result>(
        _ message: Transaction_UpdateTransactionRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Transaction_UpdateTransactionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Transaction_UpdateTransactionRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.updateTransaction(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "DeleteTransaction" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > DeleteTransaction удаление транзакции
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func deleteTransaction<Result>(
        _ message: Transaction_DeleteTransactionRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Transaction_DeleteTransactionResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Transaction_DeleteTransactionRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.deleteTransaction(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}