// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: proto/enums/errorCategory.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum ErrorCategory_ErrorCategory: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0

  /// Внутренняя ошибка сервера
  case `internal` // = 1

  /// Требуется разлогинить пользователя
  case needToLogout // = 2

  /// Требуется синхронизация устройства
  case needToSync // = 3

  /// Прочие ошибки
  case other // = 4

  /// Требуется обновить access-токен
  case needToRefreshToken // = 5
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .internal
    case 2: self = .needToLogout
    case 3: self = .needToSync
    case 4: self = .other
    case 5: self = .needToRefreshToken
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .internal: return 1
    case .needToLogout: return 2
    case .needToSync: return 3
    case .other: return 4
    case .needToRefreshToken: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [ErrorCategory_ErrorCategory] = [
    .unspecified,
    .internal,
    .needToLogout,
    .needToSync,
    .other,
    .needToRefreshToken,
  ]

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension ErrorCategory_ErrorCategory: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "Unspecified"),
    1: .same(proto: "Internal"),
    2: .same(proto: "NeedToLogout"),
    3: .same(proto: "NeedToSync"),
    4: .same(proto: "Other"),
    5: .same(proto: "NeedToRefreshToken"),
  ]
}
