// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: proto/pendingLinkedTransfer/pendingLinkedTransfer-endpoint.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - pendingLinkedTransfer.PendingLinkedTransferEndpoint

/// Namespace containing generated types for the "pendingLinkedTransfer.PendingLinkedTransferEndpoint" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum PendingLinkedTransfer_PendingLinkedTransferEndpoint: Sendable {
    /// Service descriptor for the "pendingLinkedTransfer.PendingLinkedTransferEndpoint" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "pendingLinkedTransfer.PendingLinkedTransferEndpoint")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "GetPendingLinkedTransfers" metadata.
        public enum GetPendingLinkedTransfers: Sendable {
            /// Request type for "GetPendingLinkedTransfers".
            public typealias Input = PendingLinkedTransfer_GetPendingLinkedTransfersRequest
            /// Response type for "GetPendingLinkedTransfers".
            public typealias Output = PendingLinkedTransfer_GetPendingLinkedTransfersResponse
            /// Descriptor for "GetPendingLinkedTransfers".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "pendingLinkedTransfer.PendingLinkedTransferEndpoint"),
                method: "GetPendingLinkedTransfers",
                type: .unary
            )
        }
        /// Namespace for "CreatePendingLinkedTransfer" metadata.
        public enum CreatePendingLinkedTransfer: Sendable {
            /// Request type for "CreatePendingLinkedTransfer".
            public typealias Input = PendingLinkedTransfer_CreatePendingLinkedTransferRequest
            /// Response type for "CreatePendingLinkedTransfer".
            public typealias Output = PendingLinkedTransfer_CreatePendingLinkedTransferResponse
            /// Descriptor for "CreatePendingLinkedTransfer".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "pendingLinkedTransfer.PendingLinkedTransferEndpoint"),
                method: "CreatePendingLinkedTransfer",
                type: .unary
            )
        }
        /// Namespace for "UpdatePendingLinkedTransfer" metadata.
        public enum UpdatePendingLinkedTransfer: Sendable {
            /// Request type for "UpdatePendingLinkedTransfer".
            public typealias Input = PendingLinkedTransfer_UpdatePendingLinkedTransferRequest
            /// Response type for "UpdatePendingLinkedTransfer".
            public typealias Output = PendingLinkedTransfer_UpdatePendingLinkedTransferResponse
            /// Descriptor for "UpdatePendingLinkedTransfer".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "pendingLinkedTransfer.PendingLinkedTransferEndpoint"),
                method: "UpdatePendingLinkedTransfer",
                type: .unary
            )
        }
        /// Namespace for "DeletePendingLinkedTransfer" metadata.
        public enum DeletePendingLinkedTransfer: Sendable {
            /// Request type for "DeletePendingLinkedTransfer".
            public typealias Input = PendingLinkedTransfer_DeletePendingLinkedTransferRequest
            /// Response type for "DeletePendingLinkedTransfer".
            public typealias Output = PendingLinkedTransfer_DeletePendingLinkedTransferResponse
            /// Descriptor for "DeletePendingLinkedTransfer".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "pendingLinkedTransfer.PendingLinkedTransferEndpoint"),
                method: "DeletePendingLinkedTransfer",
                type: .unary
            )
        }
        /// Descriptors for all methods in the "pendingLinkedTransfer.PendingLinkedTransferEndpoint" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            GetPendingLinkedTransfers.descriptor,
            CreatePendingLinkedTransfer.descriptor,
            UpdatePendingLinkedTransfer.descriptor,
            DeletePendingLinkedTransfer.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "pendingLinkedTransfer.PendingLinkedTransferEndpoint" service.
    public static let pendingLinkedTransfer_PendingLinkedTransferEndpoint = GRPCCore.ServiceDescriptor(fullyQualifiedService: "pendingLinkedTransfer.PendingLinkedTransferEndpoint")
}

// MARK: pendingLinkedTransfer.PendingLinkedTransferEndpoint (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension PendingLinkedTransfer_PendingLinkedTransferEndpoint {
    /// Generated client protocol for the "pendingLinkedTransfer.PendingLinkedTransferEndpoint" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Бэкенд для этой сущности — тупая точка правды с CRUD, без проверок доступа/членства в группе:
    /// > вся оркестрация (когда создавать перенос, кому он адресован) — на фронтенде.
    public protocol ClientProtocol: Sendable {
        /// Call the "GetPendingLinkedTransfers" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > GetPendingLinkedTransfers получение переносов по фильтрам
        ///
        /// - Parameters:
        ///   - request: A request containing a single `PendingLinkedTransfer_GetPendingLinkedTransfersRequest` message.
        ///   - serializer: A serializer for `PendingLinkedTransfer_GetPendingLinkedTransfersRequest` messages.
        ///   - deserializer: A deserializer for `PendingLinkedTransfer_GetPendingLinkedTransfersResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getPendingLinkedTransfers<Result>(
            request: GRPCCore.ClientRequest<PendingLinkedTransfer_GetPendingLinkedTransfersRequest>,
            serializer: some GRPCCore.MessageSerializer<PendingLinkedTransfer_GetPendingLinkedTransfersRequest>,
            deserializer: some GRPCCore.MessageDeserializer<PendingLinkedTransfer_GetPendingLinkedTransfersResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<PendingLinkedTransfer_GetPendingLinkedTransfersResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "CreatePendingLinkedTransfer" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > CreatePendingLinkedTransfer создаёт требование довнесения
        ///
        /// - Parameters:
        ///   - request: A request containing a single `PendingLinkedTransfer_CreatePendingLinkedTransferRequest` message.
        ///   - serializer: A serializer for `PendingLinkedTransfer_CreatePendingLinkedTransferRequest` messages.
        ///   - deserializer: A deserializer for `PendingLinkedTransfer_CreatePendingLinkedTransferResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func createPendingLinkedTransfer<Result>(
            request: GRPCCore.ClientRequest<PendingLinkedTransfer_CreatePendingLinkedTransferRequest>,
            serializer: some GRPCCore.MessageSerializer<PendingLinkedTransfer_CreatePendingLinkedTransferRequest>,
            deserializer: some GRPCCore.MessageDeserializer<PendingLinkedTransfer_CreatePendingLinkedTransferResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<PendingLinkedTransfer_CreatePendingLinkedTransferResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "UpdatePendingLinkedTransfer" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > UpdatePendingLinkedTransfer меняет статус переноса (Completed/Ignored)
        ///
        /// - Parameters:
        ///   - request: A request containing a single `PendingLinkedTransfer_UpdatePendingLinkedTransferRequest` message.
        ///   - serializer: A serializer for `PendingLinkedTransfer_UpdatePendingLinkedTransferRequest` messages.
        ///   - deserializer: A deserializer for `PendingLinkedTransfer_UpdatePendingLinkedTransferResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func updatePendingLinkedTransfer<Result>(
            request: GRPCCore.ClientRequest<PendingLinkedTransfer_UpdatePendingLinkedTransferRequest>,
            serializer: some GRPCCore.MessageSerializer<PendingLinkedTransfer_UpdatePendingLinkedTransferRequest>,
            deserializer: some GRPCCore.MessageDeserializer<PendingLinkedTransfer_UpdatePendingLinkedTransferResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<PendingLinkedTransfer_UpdatePendingLinkedTransferResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "DeletePendingLinkedTransfer" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > DeletePendingLinkedTransfer удаляет перенос (например, если удалили саму транзакцию-инициатор)
        ///
        /// - Parameters:
        ///   - request: A request containing a single `PendingLinkedTransfer_DeletePendingLinkedTransferRequest` message.
        ///   - serializer: A serializer for `PendingLinkedTransfer_DeletePendingLinkedTransferRequest` messages.
        ///   - deserializer: A deserializer for `PendingLinkedTransfer_DeletePendingLinkedTransferResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func deletePendingLinkedTransfer<Result>(
            request: GRPCCore.ClientRequest<PendingLinkedTransfer_DeletePendingLinkedTransferRequest>,
            serializer: some GRPCCore.MessageSerializer<PendingLinkedTransfer_DeletePendingLinkedTransferRequest>,
            deserializer: some GRPCCore.MessageDeserializer<PendingLinkedTransfer_DeletePendingLinkedTransferResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<PendingLinkedTransfer_DeletePendingLinkedTransferResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "pendingLinkedTransfer.PendingLinkedTransferEndpoint" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Бэкенд для этой сущности — тупая точка правды с CRUD, без проверок доступа/членства в группе:
    /// > вся оркестрация (когда создавать перенос, кому он адресован) — на фронтенде.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "GetPendingLinkedTransfers" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > GetPendingLinkedTransfers получение переносов по фильтрам
        ///
        /// - Parameters:
        ///   - request: A request containing a single `PendingLinkedTransfer_GetPendingLinkedTransfersRequest` message.
        ///   - serializer: A serializer for `PendingLinkedTransfer_GetPendingLinkedTransfersRequest` messages.
        ///   - deserializer: A deserializer for `PendingLinkedTransfer_GetPendingLinkedTransfersResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getPendingLinkedTransfers<Result>(
            request: GRPCCore.ClientRequest<PendingLinkedTransfer_GetPendingLinkedTransfersRequest>,
            serializer: some GRPCCore.MessageSerializer<PendingLinkedTransfer_GetPendingLinkedTransfersRequest>,
            deserializer: some GRPCCore.MessageDeserializer<PendingLinkedTransfer_GetPendingLinkedTransfersResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<PendingLinkedTransfer_GetPendingLinkedTransfersResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: PendingLinkedTransfer_PendingLinkedTransferEndpoint.Method.GetPendingLinkedTransfers.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "CreatePendingLinkedTransfer" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > CreatePendingLinkedTransfer создаёт требование довнесения
        ///
        /// - Parameters:
        ///   - request: A request containing a single `PendingLinkedTransfer_CreatePendingLinkedTransferRequest` message.
        ///   - serializer: A serializer for `PendingLinkedTransfer_CreatePendingLinkedTransferRequest` messages.
        ///   - deserializer: A deserializer for `PendingLinkedTransfer_CreatePendingLinkedTransferResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func createPendingLinkedTransfer<Result>(
            request: GRPCCore.ClientRequest<PendingLinkedTransfer_CreatePendingLinkedTransferRequest>,
            serializer: some GRPCCore.MessageSerializer<PendingLinkedTransfer_CreatePendingLinkedTransferRequest>,
            deserializer: some GRPCCore.MessageDeserializer<PendingLinkedTransfer_CreatePendingLinkedTransferResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<PendingLinkedTransfer_CreatePendingLinkedTransferResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: PendingLinkedTransfer_PendingLinkedTransferEndpoint.Method.CreatePendingLinkedTransfer.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "UpdatePendingLinkedTransfer" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > UpdatePendingLinkedTransfer меняет статус переноса (Completed/Ignored)
        ///
        /// - Parameters:
        ///   - request: A request containing a single `PendingLinkedTransfer_UpdatePendingLinkedTransferRequest` message.
        ///   - serializer: A serializer for `PendingLinkedTransfer_UpdatePendingLinkedTransferRequest` messages.
        ///   - deserializer: A deserializer for `PendingLinkedTransfer_UpdatePendingLinkedTransferResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func updatePendingLinkedTransfer<Result>(
            request: GRPCCore.ClientRequest<PendingLinkedTransfer_UpdatePendingLinkedTransferRequest>,
            serializer: some GRPCCore.MessageSerializer<PendingLinkedTransfer_UpdatePendingLinkedTransferRequest>,
            deserializer: some GRPCCore.MessageDeserializer<PendingLinkedTransfer_UpdatePendingLinkedTransferResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<PendingLinkedTransfer_UpdatePendingLinkedTransferResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: PendingLinkedTransfer_PendingLinkedTransferEndpoint.Method.UpdatePendingLinkedTransfer.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "DeletePendingLinkedTransfer" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > DeletePendingLinkedTransfer удаляет перенос (например, если удалили саму транзакцию-инициатор)
        ///
        /// - Parameters:
        ///   - request: A request containing a single `PendingLinkedTransfer_DeletePendingLinkedTransferRequest` message.
        ///   - serializer: A serializer for `PendingLinkedTransfer_DeletePendingLinkedTransferRequest` messages.
        ///   - deserializer: A deserializer for `PendingLinkedTransfer_DeletePendingLinkedTransferResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func deletePendingLinkedTransfer<Result>(
            request: GRPCCore.ClientRequest<PendingLinkedTransfer_DeletePendingLinkedTransferRequest>,
            serializer: some GRPCCore.MessageSerializer<PendingLinkedTransfer_DeletePendingLinkedTransferRequest>,
            deserializer: some GRPCCore.MessageDeserializer<PendingLinkedTransfer_DeletePendingLinkedTransferResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<PendingLinkedTransfer_DeletePendingLinkedTransferResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: PendingLinkedTransfer_PendingLinkedTransferEndpoint.Method.DeletePendingLinkedTransfer.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension PendingLinkedTransfer_PendingLinkedTransferEndpoint.ClientProtocol {
    /// Call the "GetPendingLinkedTransfers" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > GetPendingLinkedTransfers получение переносов по фильтрам
    ///
    /// - Parameters:
    ///   - request: A request containing a single `PendingLinkedTransfer_GetPendingLinkedTransfersRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getPendingLinkedTransfers<Result>(
        request: GRPCCore.ClientRequest<PendingLinkedTransfer_GetPendingLinkedTransfersRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<PendingLinkedTransfer_GetPendingLinkedTransfersResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getPendingLinkedTransfers(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<PendingLinkedTransfer_GetPendingLinkedTransfersRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<PendingLinkedTransfer_GetPendingLinkedTransfersResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CreatePendingLinkedTransfer" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > CreatePendingLinkedTransfer создаёт требование довнесения
    ///
    /// - Parameters:
    ///   - request: A request containing a single `PendingLinkedTransfer_CreatePendingLinkedTransferRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func createPendingLinkedTransfer<Result>(
        request: GRPCCore.ClientRequest<PendingLinkedTransfer_CreatePendingLinkedTransferRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<PendingLinkedTransfer_CreatePendingLinkedTransferResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.createPendingLinkedTransfer(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<PendingLinkedTransfer_CreatePendingLinkedTransferRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<PendingLinkedTransfer_CreatePendingLinkedTransferResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdatePendingLinkedTransfer" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > UpdatePendingLinkedTransfer меняет статус переноса (Completed/Ignored)
    ///
    /// - Parameters:
    ///   - request: A request containing a single `PendingLinkedTransfer_UpdatePendingLinkedTransferRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func updatePendingLinkedTransfer<Result>(
        request: GRPCCore.ClientRequest<PendingLinkedTransfer_UpdatePendingLinkedTransferRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<PendingLinkedTransfer_UpdatePendingLinkedTransferResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.updatePendingLinkedTransfer(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<PendingLinkedTransfer_UpdatePendingLinkedTransferRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<PendingLinkedTransfer_UpdatePendingLinkedTransferResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "DeletePendingLinkedTransfer" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > DeletePendingLinkedTransfer удаляет перенос (например, если удалили саму транзакцию-инициатор)
    ///
    /// - Parameters:
    ///   - request: A request containing a single `PendingLinkedTransfer_DeletePendingLinkedTransferRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func deletePendingLinkedTransfer<Result>(
        request: GRPCCore.ClientRequest<PendingLinkedTransfer_DeletePendingLinkedTransferRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<PendingLinkedTransfer_DeletePendingLinkedTransferResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.deletePendingLinkedTransfer(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<PendingLinkedTransfer_DeletePendingLinkedTransferRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<PendingLinkedTransfer_DeletePendingLinkedTransferResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension PendingLinkedTransfer_PendingLinkedTransferEndpoint.ClientProtocol {
    /// Call the "GetPendingLinkedTransfers" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > GetPendingLinkedTransfers получение переносов по фильтрам
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getPendingLinkedTransfers<Result>(
        _ message: PendingLinkedTransfer_GetPendingLinkedTransfersRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<PendingLinkedTransfer_GetPendingLinkedTransfersResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<PendingLinkedTransfer_GetPendingLinkedTransfersRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getPendingLinkedTransfers(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CreatePendingLinkedTransfer" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > CreatePendingLinkedTransfer создаёт требование довнесения
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func createPendingLinkedTransfer<Result>(
        _ message: PendingLinkedTransfer_CreatePendingLinkedTransferRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<PendingLinkedTransfer_CreatePendingLinkedTransferResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<PendingLinkedTransfer_CreatePendingLinkedTransferRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.createPendingLinkedTransfer(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdatePendingLinkedTransfer" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > UpdatePendingLinkedTransfer меняет статус переноса (Completed/Ignored)
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func updatePendingLinkedTransfer<Result>(
        _ message: PendingLinkedTransfer_UpdatePendingLinkedTransferRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<PendingLinkedTransfer_UpdatePendingLinkedTransferResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<PendingLinkedTransfer_UpdatePendingLinkedTransferRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.updatePendingLinkedTransfer(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "DeletePendingLinkedTransfer" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > DeletePendingLinkedTransfer удаляет перенос (например, если удалили саму транзакцию-инициатор)
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func deletePendingLinkedTransfer<Result>(
        _ message: PendingLinkedTransfer_DeletePendingLinkedTransferRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<PendingLinkedTransfer_DeletePendingLinkedTransferResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<PendingLinkedTransfer_DeletePendingLinkedTransferRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.deletePendingLinkedTransfer(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}