// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: proto/usersToAccountGroup/usersToAccountGroup-endpoint.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - usersToAccountGroup.UsersToAccountGroupEndpoint

/// Namespace containing generated types for the "usersToAccountGroup.UsersToAccountGroupEndpoint" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum UsersToAccountGroup_UsersToAccountGroupEndpoint: Sendable {
    /// Service descriptor for the "usersToAccountGroup.UsersToAccountGroupEndpoint" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "usersToAccountGroup.UsersToAccountGroupEndpoint")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "GetUsersToAccountGroup" metadata.
        public enum GetUsersToAccountGroup: Sendable {
            /// Request type for "GetUsersToAccountGroup".
            public typealias Input = UsersToAccountGroup_GetUsersToAccountGroupRequest
            /// Response type for "GetUsersToAccountGroup".
            public typealias Output = UsersToAccountGroup_GetUsersToAccountGroupResponse
            /// Descriptor for "GetUsersToAccountGroup".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "usersToAccountGroup.UsersToAccountGroupEndpoint"),
                method: "GetUsersToAccountGroup",
                type: .unary
            )
        }
        /// Namespace for "AddUserToAccountGroup" metadata.
        public enum AddUserToAccountGroup: Sendable {
            /// Request type for "AddUserToAccountGroup".
            public typealias Input = UsersToAccountGroup_AddUserToAccountGroupRequest
            /// Response type for "AddUserToAccountGroup".
            public typealias Output = UsersToAccountGroup_AddUserToAccountGroupResponse
            /// Descriptor for "AddUserToAccountGroup".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "usersToAccountGroup.UsersToAccountGroupEndpoint"),
                method: "AddUserToAccountGroup",
                type: .unary
            )
        }
        /// Namespace for "RemoveUserFromAccountGroup" metadata.
        public enum RemoveUserFromAccountGroup: Sendable {
            /// Request type for "RemoveUserFromAccountGroup".
            public typealias Input = UsersToAccountGroup_RemoveUserFromAccountGroupRequest
            /// Response type for "RemoveUserFromAccountGroup".
            public typealias Output = UsersToAccountGroup_RemoveUserFromAccountGroupResponse
            /// Descriptor for "RemoveUserFromAccountGroup".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "usersToAccountGroup.UsersToAccountGroupEndpoint"),
                method: "RemoveUserFromAccountGroup",
                type: .unary
            )
        }
        /// Descriptors for all methods in the "usersToAccountGroup.UsersToAccountGroupEndpoint" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            GetUsersToAccountGroup.descriptor,
            AddUserToAccountGroup.descriptor,
            RemoveUserFromAccountGroup.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "usersToAccountGroup.UsersToAccountGroupEndpoint" service.
    public static let usersToAccountGroup_UsersToAccountGroupEndpoint = GRPCCore.ServiceDescriptor(fullyQualifiedService: "usersToAccountGroup.UsersToAccountGroupEndpoint")
}

// MARK: usersToAccountGroup.UsersToAccountGroupEndpoint (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension UsersToAccountGroup_UsersToAccountGroupEndpoint {
    /// Generated client protocol for the "usersToAccountGroup.UsersToAccountGroupEndpoint" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Связь "пользователь состоит в группе счетов" — отдельная сущность/модуль, не часть
    /// > accountGroup: используется как единственная точка правды для видимости и прав доступа во всех
    /// > местах, где данные пересекают границу одного пользователя (счета-мосты и pendingLinkedTransfer,
    /// > в перспективе — любой другой шаринг данных между людьми).
    public protocol ClientProtocol: Sendable {
        /// Call the "GetUsersToAccountGroup" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > GetUsersToAccountGroup возвращает участников группы счетов — источник кандидатов для
        /// > линковки счёта-моста (account.UpdateAccountRequest.linkedAccountID) и точка проверки
        /// > видимости pendingLinkedTransfer на бэкенде.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `UsersToAccountGroup_GetUsersToAccountGroupRequest` message.
        ///   - serializer: A serializer for `UsersToAccountGroup_GetUsersToAccountGroupRequest` messages.
        ///   - deserializer: A deserializer for `UsersToAccountGroup_GetUsersToAccountGroupResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getUsersToAccountGroup<Result>(
            request: GRPCCore.ClientRequest<UsersToAccountGroup_GetUsersToAccountGroupRequest>,
            serializer: some GRPCCore.MessageSerializer<UsersToAccountGroup_GetUsersToAccountGroupRequest>,
            deserializer: some GRPCCore.MessageDeserializer<UsersToAccountGroup_GetUsersToAccountGroupResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UsersToAccountGroup_GetUsersToAccountGroupResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "AddUserToAccountGroup" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > AddUserToAccountGroup добавляет пользователя в группу счетов. Кто именно может это вызывать
        /// > (только существующий участник?) и нужен ли отдельный флоу приглашения/подтверждения —
        /// > определяется бэкендом, контракт этого не ограничивает.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `UsersToAccountGroup_AddUserToAccountGroupRequest` message.
        ///   - serializer: A serializer for `UsersToAccountGroup_AddUserToAccountGroupRequest` messages.
        ///   - deserializer: A deserializer for `UsersToAccountGroup_AddUserToAccountGroupResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func addUserToAccountGroup<Result>(
            request: GRPCCore.ClientRequest<UsersToAccountGroup_AddUserToAccountGroupRequest>,
            serializer: some GRPCCore.MessageSerializer<UsersToAccountGroup_AddUserToAccountGroupRequest>,
            deserializer: some GRPCCore.MessageDeserializer<UsersToAccountGroup_AddUserToAccountGroupResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UsersToAccountGroup_AddUserToAccountGroupResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "RemoveUserFromAccountGroup" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > RemoveUserFromAccountGroup убирает пользователя из группы счетов (выход самого пользователя,
        /// > либо удаление другим участником — авторизация на бэкенде).
        ///
        /// - Parameters:
        ///   - request: A request containing a single `UsersToAccountGroup_RemoveUserFromAccountGroupRequest` message.
        ///   - serializer: A serializer for `UsersToAccountGroup_RemoveUserFromAccountGroupRequest` messages.
        ///   - deserializer: A deserializer for `UsersToAccountGroup_RemoveUserFromAccountGroupResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func removeUserFromAccountGroup<Result>(
            request: GRPCCore.ClientRequest<UsersToAccountGroup_RemoveUserFromAccountGroupRequest>,
            serializer: some GRPCCore.MessageSerializer<UsersToAccountGroup_RemoveUserFromAccountGroupRequest>,
            deserializer: some GRPCCore.MessageDeserializer<UsersToAccountGroup_RemoveUserFromAccountGroupResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UsersToAccountGroup_RemoveUserFromAccountGroupResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "usersToAccountGroup.UsersToAccountGroupEndpoint" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Связь "пользователь состоит в группе счетов" — отдельная сущность/модуль, не часть
    /// > accountGroup: используется как единственная точка правды для видимости и прав доступа во всех
    /// > местах, где данные пересекают границу одного пользователя (счета-мосты и pendingLinkedTransfer,
    /// > в перспективе — любой другой шаринг данных между людьми).
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "GetUsersToAccountGroup" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > GetUsersToAccountGroup возвращает участников группы счетов — источник кандидатов для
        /// > линковки счёта-моста (account.UpdateAccountRequest.linkedAccountID) и точка проверки
        /// > видимости pendingLinkedTransfer на бэкенде.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `UsersToAccountGroup_GetUsersToAccountGroupRequest` message.
        ///   - serializer: A serializer for `UsersToAccountGroup_GetUsersToAccountGroupRequest` messages.
        ///   - deserializer: A deserializer for `UsersToAccountGroup_GetUsersToAccountGroupResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getUsersToAccountGroup<Result>(
            request: GRPCCore.ClientRequest<UsersToAccountGroup_GetUsersToAccountGroupRequest>,
            serializer: some GRPCCore.MessageSerializer<UsersToAccountGroup_GetUsersToAccountGroupRequest>,
            deserializer: some GRPCCore.MessageDeserializer<UsersToAccountGroup_GetUsersToAccountGroupResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UsersToAccountGroup_GetUsersToAccountGroupResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: UsersToAccountGroup_UsersToAccountGroupEndpoint.Method.GetUsersToAccountGroup.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "AddUserToAccountGroup" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > AddUserToAccountGroup добавляет пользователя в группу счетов. Кто именно может это вызывать
        /// > (только существующий участник?) и нужен ли отдельный флоу приглашения/подтверждения —
        /// > определяется бэкендом, контракт этого не ограничивает.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `UsersToAccountGroup_AddUserToAccountGroupRequest` message.
        ///   - serializer: A serializer for `UsersToAccountGroup_AddUserToAccountGroupRequest` messages.
        ///   - deserializer: A deserializer for `UsersToAccountGroup_AddUserToAccountGroupResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func addUserToAccountGroup<Result>(
            request: GRPCCore.ClientRequest<UsersToAccountGroup_AddUserToAccountGroupRequest>,
            serializer: some GRPCCore.MessageSerializer<UsersToAccountGroup_AddUserToAccountGroupRequest>,
            deserializer: some GRPCCore.MessageDeserializer<UsersToAccountGroup_AddUserToAccountGroupResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UsersToAccountGroup_AddUserToAccountGroupResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: UsersToAccountGroup_UsersToAccountGroupEndpoint.Method.AddUserToAccountGroup.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "RemoveUserFromAccountGroup" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > RemoveUserFromAccountGroup убирает пользователя из группы счетов (выход самого пользователя,
        /// > либо удаление другим участником — авторизация на бэкенде).
        ///
        /// - Parameters:
        ///   - request: A request containing a single `UsersToAccountGroup_RemoveUserFromAccountGroupRequest` message.
        ///   - serializer: A serializer for `UsersToAccountGroup_RemoveUserFromAccountGroupRequest` messages.
        ///   - deserializer: A deserializer for `UsersToAccountGroup_RemoveUserFromAccountGroupResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func removeUserFromAccountGroup<Result>(
            request: GRPCCore.ClientRequest<UsersToAccountGroup_RemoveUserFromAccountGroupRequest>,
            serializer: some GRPCCore.MessageSerializer<UsersToAccountGroup_RemoveUserFromAccountGroupRequest>,
            deserializer: some GRPCCore.MessageDeserializer<UsersToAccountGroup_RemoveUserFromAccountGroupResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UsersToAccountGroup_RemoveUserFromAccountGroupResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: UsersToAccountGroup_UsersToAccountGroupEndpoint.Method.RemoveUserFromAccountGroup.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension UsersToAccountGroup_UsersToAccountGroupEndpoint.ClientProtocol {
    /// Call the "GetUsersToAccountGroup" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > GetUsersToAccountGroup возвращает участников группы счетов — источник кандидатов для
    /// > линковки счёта-моста (account.UpdateAccountRequest.linkedAccountID) и точка проверки
    /// > видимости pendingLinkedTransfer на бэкенде.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `UsersToAccountGroup_GetUsersToAccountGroupRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getUsersToAccountGroup<Result>(
        request: GRPCCore.ClientRequest<UsersToAccountGroup_GetUsersToAccountGroupRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UsersToAccountGroup_GetUsersToAccountGroupResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getUsersToAccountGroup(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<UsersToAccountGroup_GetUsersToAccountGroupRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<UsersToAccountGroup_GetUsersToAccountGroupResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "AddUserToAccountGroup" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > AddUserToAccountGroup добавляет пользователя в группу счетов. Кто именно может это вызывать
    /// > (только существующий участник?) и нужен ли отдельный флоу приглашения/подтверждения —
    /// > определяется бэкендом, контракт этого не ограничивает.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `UsersToAccountGroup_AddUserToAccountGroupRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func addUserToAccountGroup<Result>(
        request: GRPCCore.ClientRequest<UsersToAccountGroup_AddUserToAccountGroupRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UsersToAccountGroup_AddUserToAccountGroupResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.addUserToAccountGroup(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<UsersToAccountGroup_AddUserToAccountGroupRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<UsersToAccountGroup_AddUserToAccountGroupResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "RemoveUserFromAccountGroup" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > RemoveUserFromAccountGroup убирает пользователя из группы счетов (выход самого пользователя,
    /// > либо удаление другим участником — авторизация на бэкенде).
    ///
    /// - Parameters:
    ///   - request: A request containing a single `UsersToAccountGroup_RemoveUserFromAccountGroupRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func removeUserFromAccountGroup<Result>(
        request: GRPCCore.ClientRequest<UsersToAccountGroup_RemoveUserFromAccountGroupRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UsersToAccountGroup_RemoveUserFromAccountGroupResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.removeUserFromAccountGroup(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<UsersToAccountGroup_RemoveUserFromAccountGroupRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<UsersToAccountGroup_RemoveUserFromAccountGroupResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension UsersToAccountGroup_UsersToAccountGroupEndpoint.ClientProtocol {
    /// Call the "GetUsersToAccountGroup" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > GetUsersToAccountGroup возвращает участников группы счетов — источник кандидатов для
    /// > линковки счёта-моста (account.UpdateAccountRequest.linkedAccountID) и точка проверки
    /// > видимости pendingLinkedTransfer на бэкенде.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getUsersToAccountGroup<Result>(
        _ message: UsersToAccountGroup_GetUsersToAccountGroupRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UsersToAccountGroup_GetUsersToAccountGroupResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<UsersToAccountGroup_GetUsersToAccountGroupRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getUsersToAccountGroup(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "AddUserToAccountGroup" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > AddUserToAccountGroup добавляет пользователя в группу счетов. Кто именно может это вызывать
    /// > (только существующий участник?) и нужен ли отдельный флоу приглашения/подтверждения —
    /// > определяется бэкендом, контракт этого не ограничивает.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func addUserToAccountGroup<Result>(
        _ message: UsersToAccountGroup_AddUserToAccountGroupRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UsersToAccountGroup_AddUserToAccountGroupResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<UsersToAccountGroup_AddUserToAccountGroupRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.addUserToAccountGroup(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "RemoveUserFromAccountGroup" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > RemoveUserFromAccountGroup убирает пользователя из группы счетов (выход самого пользователя,
    /// > либо удаление другим участником — авторизация на бэкенде).
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func removeUserFromAccountGroup<Result>(
        _ message: UsersToAccountGroup_RemoveUserFromAccountGroupRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UsersToAccountGroup_RemoveUserFromAccountGroupResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<UsersToAccountGroup_RemoveUserFromAccountGroupRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.removeUserFromAccountGroup(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}