// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: proto/account/account-endpoint.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - account.AccountEndpoint

/// Namespace containing generated types for the "account.AccountEndpoint" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Account_AccountEndpoint: Sendable {
    /// Service descriptor for the "account.AccountEndpoint" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "account.AccountEndpoint")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "GetAccounts" metadata.
        public enum GetAccounts: Sendable {
            /// Request type for "GetAccounts".
            public typealias Input = Account_GetAccountsRequest
            /// Response type for "GetAccounts".
            public typealias Output = Account_GetAccountsResponse
            /// Descriptor for "GetAccounts".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "account.AccountEndpoint"),
                method: "GetAccounts",
                type: .unary
            )
        }
        /// Namespace for "CreateAccount" metadata.
        public enum CreateAccount: Sendable {
            /// Request type for "CreateAccount".
            public typealias Input = Account_CreateAccountRequest
            /// Response type for "CreateAccount".
            public typealias Output = Account_CreateAccountResponse
            /// Descriptor for "CreateAccount".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "account.AccountEndpoint"),
                method: "CreateAccount",
                type: .unary
            )
        }
        /// Namespace for "UpdateAccount" metadata.
        public enum UpdateAccount: Sendable {
            /// Request type for "UpdateAccount".
            public typealias Input = Account_UpdateAccountRequest
            /// Response type for "UpdateAccount".
            public typealias Output = Account_UpdateAccountResponse
            /// Descriptor for "UpdateAccount".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "account.AccountEndpoint"),
                method: "UpdateAccount",
                type: .unary
            )
        }
        /// Namespace for "DeleteAccount" metadata.
        public enum DeleteAccount: Sendable {
            /// Request type for "DeleteAccount".
            public typealias Input = Account_DeleteAccountRequest
            /// Response type for "DeleteAccount".
            public typealias Output = Account_DeleteAccountResponse
            /// Descriptor for "DeleteAccount".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "account.AccountEndpoint"),
                method: "DeleteAccount",
                type: .unary
            )
        }
        /// Descriptors for all methods in the "account.AccountEndpoint" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            GetAccounts.descriptor,
            CreateAccount.descriptor,
            UpdateAccount.descriptor,
            DeleteAccount.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "account.AccountEndpoint" service.
    public static let account_AccountEndpoint = GRPCCore.ServiceDescriptor(fullyQualifiedService: "account.AccountEndpoint")
}

// MARK: account.AccountEndpoint (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Account_AccountEndpoint {
    /// Generated client protocol for the "account.AccountEndpoint" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "GetAccounts" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > GetAccounts получение счетов по фильтрам
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Account_GetAccountsRequest` message.
        ///   - serializer: A serializer for `Account_GetAccountsRequest` messages.
        ///   - deserializer: A deserializer for `Account_GetAccountsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getAccounts<Result>(
            request: GRPCCore.ClientRequest<Account_GetAccountsRequest>,
            serializer: some GRPCCore.MessageSerializer<Account_GetAccountsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Account_GetAccountsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Account_GetAccountsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "CreateAccount" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > CreateAccount создание счета
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Account_CreateAccountRequest` message.
        ///   - serializer: A serializer for `Account_CreateAccountRequest` messages.
        ///   - deserializer: A deserializer for `Account_CreateAccountResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func createAccount<Result>(
            request: GRPCCore.ClientRequest<Account_CreateAccountRequest>,
            serializer: some GRPCCore.MessageSerializer<Account_CreateAccountRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Account_CreateAccountResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Account_CreateAccountResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "UpdateAccount" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > UpdateAccount редактирование счета
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Account_UpdateAccountRequest` message.
        ///   - serializer: A serializer for `Account_UpdateAccountRequest` messages.
        ///   - deserializer: A deserializer for `Account_UpdateAccountResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func updateAccount<Result>(
            request: GRPCCore.ClientRequest<Account_UpdateAccountRequest>,
            serializer: some GRPCCore.MessageSerializer<Account_UpdateAccountRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Account_UpdateAccountResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Account_UpdateAccountResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "DeleteAccount" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > DeleteAccount удаление счета
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Account_DeleteAccountRequest` message.
        ///   - serializer: A serializer for `Account_DeleteAccountRequest` messages.
        ///   - deserializer: A deserializer for `Account_DeleteAccountResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func deleteAccount<Result>(
            request: GRPCCore.ClientRequest<Account_DeleteAccountRequest>,
            serializer: some GRPCCore.MessageSerializer<Account_DeleteAccountRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Account_DeleteAccountResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Account_DeleteAccountResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "account.AccountEndpoint" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "GetAccounts" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > GetAccounts получение счетов по фильтрам
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Account_GetAccountsRequest` message.
        ///   - serializer: A serializer for `Account_GetAccountsRequest` messages.
        ///   - deserializer: A deserializer for `Account_GetAccountsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getAccounts<Result>(
            request: GRPCCore.ClientRequest<Account_GetAccountsRequest>,
            serializer: some GRPCCore.MessageSerializer<Account_GetAccountsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Account_GetAccountsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Account_GetAccountsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Account_AccountEndpoint.Method.GetAccounts.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "CreateAccount" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > CreateAccount создание счета
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Account_CreateAccountRequest` message.
        ///   - serializer: A serializer for `Account_CreateAccountRequest` messages.
        ///   - deserializer: A deserializer for `Account_CreateAccountResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func createAccount<Result>(
            request: GRPCCore.ClientRequest<Account_CreateAccountRequest>,
            serializer: some GRPCCore.MessageSerializer<Account_CreateAccountRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Account_CreateAccountResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Account_CreateAccountResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Account_AccountEndpoint.Method.CreateAccount.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "UpdateAccount" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > UpdateAccount редактирование счета
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Account_UpdateAccountRequest` message.
        ///   - serializer: A serializer for `Account_UpdateAccountRequest` messages.
        ///   - deserializer: A deserializer for `Account_UpdateAccountResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func updateAccount<Result>(
            request: GRPCCore.ClientRequest<Account_UpdateAccountRequest>,
            serializer: some GRPCCore.MessageSerializer<Account_UpdateAccountRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Account_UpdateAccountResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Account_UpdateAccountResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Account_AccountEndpoint.Method.UpdateAccount.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "DeleteAccount" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > DeleteAccount удаление счета
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Account_DeleteAccountRequest` message.
        ///   - serializer: A serializer for `Account_DeleteAccountRequest` messages.
        ///   - deserializer: A deserializer for `Account_DeleteAccountResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func deleteAccount<Result>(
            request: GRPCCore.ClientRequest<Account_DeleteAccountRequest>,
            serializer: some GRPCCore.MessageSerializer<Account_DeleteAccountRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Account_DeleteAccountResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Account_DeleteAccountResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Account_AccountEndpoint.Method.DeleteAccount.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Account_AccountEndpoint.ClientProtocol {
    /// Call the "GetAccounts" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > GetAccounts получение счетов по фильтрам
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Account_GetAccountsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getAccounts<Result>(
        request: GRPCCore.ClientRequest<Account_GetAccountsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Account_GetAccountsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getAccounts(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Account_GetAccountsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Account_GetAccountsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CreateAccount" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > CreateAccount создание счета
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Account_CreateAccountRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func createAccount<Result>(
        request: GRPCCore.ClientRequest<Account_CreateAccountRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Account_CreateAccountResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.createAccount(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Account_CreateAccountRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Account_CreateAccountResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdateAccount" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > UpdateAccount редактирование счета
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Account_UpdateAccountRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func updateAccount<Result>(
        request: GRPCCore.ClientRequest<Account_UpdateAccountRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Account_UpdateAccountResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.updateAccount(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Account_UpdateAccountRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Account_UpdateAccountResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "DeleteAccount" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > DeleteAccount удаление счета
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Account_DeleteAccountRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func deleteAccount<Result>(
        request: GRPCCore.ClientRequest<Account_DeleteAccountRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Account_DeleteAccountResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.deleteAccount(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Account_DeleteAccountRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Account_DeleteAccountResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Account_AccountEndpoint.ClientProtocol {
    /// Call the "GetAccounts" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > GetAccounts получение счетов по фильтрам
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getAccounts<Result>(
        _ message: Account_GetAccountsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Account_GetAccountsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Account_GetAccountsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getAccounts(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CreateAccount" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > CreateAccount создание счета
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func createAccount<Result>(
        _ message: Account_CreateAccountRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Account_CreateAccountResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Account_CreateAccountRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.createAccount(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdateAccount" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > UpdateAccount редактирование счета
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func updateAccount<Result>(
        _ message: Account_UpdateAccountRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Account_UpdateAccountResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Account_UpdateAccountRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.updateAccount(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "DeleteAccount" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > DeleteAccount удаление счета
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func deleteAccount<Result>(
        _ message: Account_DeleteAccountRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Account_DeleteAccountResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Account_DeleteAccountRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.deleteAccount(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}