// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: proto/user/user-endpoint.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - user.UserEndpoint

/// Namespace containing generated types for the "user.UserEndpoint" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum User_UserEndpoint: Sendable {
    /// Service descriptor for the "user.UserEndpoint" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "user.UserEndpoint")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "GetUser" metadata.
        public enum GetUser: Sendable {
            /// Request type for "GetUser".
            public typealias Input = User_GetUserRequest
            /// Response type for "GetUser".
            public typealias Output = User_GetUserResponse
            /// Descriptor for "GetUser".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "user.UserEndpoint"),
                method: "GetUser",
                type: .unary
            )
        }
        /// Namespace for "UpdateUser" metadata.
        public enum UpdateUser: Sendable {
            /// Request type for "UpdateUser".
            public typealias Input = User_UpdateUserRequest
            /// Response type for "UpdateUser".
            public typealias Output = User_UpdateUserResponse
            /// Descriptor for "UpdateUser".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "user.UserEndpoint"),
                method: "UpdateUser",
                type: .unary
            )
        }
        /// Descriptors for all methods in the "user.UserEndpoint" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            GetUser.descriptor,
            UpdateUser.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "user.UserEndpoint" service.
    public static let user_UserEndpoint = GRPCCore.ServiceDescriptor(fullyQualifiedService: "user.UserEndpoint")
}

// MARK: user.UserEndpoint (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension User_UserEndpoint {
    /// Generated client protocol for the "user.UserEndpoint" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "GetUser" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > GetUser получение данных пользователя
        ///
        /// - Parameters:
        ///   - request: A request containing a single `User_GetUserRequest` message.
        ///   - serializer: A serializer for `User_GetUserRequest` messages.
        ///   - deserializer: A deserializer for `User_GetUserResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getUser<Result>(
            request: GRPCCore.ClientRequest<User_GetUserRequest>,
            serializer: some GRPCCore.MessageSerializer<User_GetUserRequest>,
            deserializer: some GRPCCore.MessageDeserializer<User_GetUserResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<User_GetUserResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "UpdateUser" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > UpdateUser редактирование пользователя
        ///
        /// - Parameters:
        ///   - request: A request containing a single `User_UpdateUserRequest` message.
        ///   - serializer: A serializer for `User_UpdateUserRequest` messages.
        ///   - deserializer: A deserializer for `User_UpdateUserResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func updateUser<Result>(
            request: GRPCCore.ClientRequest<User_UpdateUserRequest>,
            serializer: some GRPCCore.MessageSerializer<User_UpdateUserRequest>,
            deserializer: some GRPCCore.MessageDeserializer<User_UpdateUserResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<User_UpdateUserResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "user.UserEndpoint" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "GetUser" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > GetUser получение данных пользователя
        ///
        /// - Parameters:
        ///   - request: A request containing a single `User_GetUserRequest` message.
        ///   - serializer: A serializer for `User_GetUserRequest` messages.
        ///   - deserializer: A deserializer for `User_GetUserResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getUser<Result>(
            request: GRPCCore.ClientRequest<User_GetUserRequest>,
            serializer: some GRPCCore.MessageSerializer<User_GetUserRequest>,
            deserializer: some GRPCCore.MessageDeserializer<User_GetUserResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<User_GetUserResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: User_UserEndpoint.Method.GetUser.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "UpdateUser" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > UpdateUser редактирование пользователя
        ///
        /// - Parameters:
        ///   - request: A request containing a single `User_UpdateUserRequest` message.
        ///   - serializer: A serializer for `User_UpdateUserRequest` messages.
        ///   - deserializer: A deserializer for `User_UpdateUserResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func updateUser<Result>(
            request: GRPCCore.ClientRequest<User_UpdateUserRequest>,
            serializer: some GRPCCore.MessageSerializer<User_UpdateUserRequest>,
            deserializer: some GRPCCore.MessageDeserializer<User_UpdateUserResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<User_UpdateUserResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: User_UserEndpoint.Method.UpdateUser.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension User_UserEndpoint.ClientProtocol {
    /// Call the "GetUser" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > GetUser получение данных пользователя
    ///
    /// - Parameters:
    ///   - request: A request containing a single `User_GetUserRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getUser<Result>(
        request: GRPCCore.ClientRequest<User_GetUserRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<User_GetUserResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getUser(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<User_GetUserRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<User_GetUserResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdateUser" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > UpdateUser редактирование пользователя
    ///
    /// - Parameters:
    ///   - request: A request containing a single `User_UpdateUserRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func updateUser<Result>(
        request: GRPCCore.ClientRequest<User_UpdateUserRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<User_UpdateUserResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.updateUser(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<User_UpdateUserRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<User_UpdateUserResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension User_UserEndpoint.ClientProtocol {
    /// Call the "GetUser" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > GetUser получение данных пользователя
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getUser<Result>(
        _ message: User_GetUserRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<User_GetUserResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<User_GetUserRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getUser(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdateUser" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > UpdateUser редактирование пользователя
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func updateUser<Result>(
        _ message: User_UpdateUserRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<User_UpdateUserResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<User_UpdateUserRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.updateUser(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}