// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: proto/accountBudget/accountBudget-endpoint.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct AccountBudget_AccountBudget: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Идентификатор версии бюджета
  public var id: Data = Data()

  /// Идентификатор счета
  public var accountID: Data = Data()

  /// Сумма бюджета
  public var amount: Double = 0

  /// Фиксированная сумма
  public var fixedSum: Double = 0

  /// Смещение в днях
  public var daysOffset: UInt32 = 0

  /// Заполняется ли бюджет постепенно
  public var gradualFilling: Bool = false

  /// Дата, с которой действует эта версия бюджета
  public var effectiveFrom: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _effectiveFrom ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_effectiveFrom = newValue}
  }
  /// Returns true if `effectiveFrom` has been explicitly set.
  public var hasEffectiveFrom: Bool {return self._effectiveFrom != nil}
  /// Clears the value of `effectiveFrom`. Subsequent reads from it will return its default value.
  public mutating func clearEffectiveFrom() {self._effectiveFrom = nil}

  /// Идентификатор пользователя, создавшего версию
  public var createdByUserID: Data = Data()

  /// Дата и время создания версии
  public var datetimeCreate: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _datetimeCreate ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_datetimeCreate = newValue}
  }
  /// Returns true if `datetimeCreate` has been explicitly set.
  public var hasDatetimeCreate: Bool {return self._datetimeCreate != nil}
  /// Clears the value of `datetimeCreate`. Subsequent reads from it will return its default value.
  public mutating func clearDatetimeCreate() {self._datetimeCreate = nil}

  /// Идентификатор группы счетов
  public var accountGroupID: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _effectiveFrom: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _datetimeCreate: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

public struct AccountBudget_CreateAccountBudgetRequest: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Токен доступа
  public var accessToken: String = String()

  /// Идентификатор версии бюджета
  public var id: Data = Data()

  /// Идентификатор счета
  public var accountID: Data = Data()

  /// Сумма бюджета
  public var amount: Double = 0

  /// Фиксированная сумма
  public var fixedSum: Double = 0

  /// Смещение в днях
  public var daysOffset: UInt32 = 0

  /// Заполняется ли бюджет постепенно
  public var gradualFilling: Bool = false

  /// Дата, с которой действует эта версия бюджета
  public var effectiveFrom: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _effectiveFrom ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_effectiveFrom = newValue}
  }
  /// Returns true if `effectiveFrom` has been explicitly set.
  public var hasEffectiveFrom: Bool {return self._effectiveFrom != nil}
  /// Clears the value of `effectiveFrom`. Subsequent reads from it will return its default value.
  public mutating func clearEffectiveFrom() {self._effectiveFrom = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _effectiveFrom: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

public struct AccountBudget_CreateAccountBudgetResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Объект ошибки
  public var error: Error_Error {
    get {return _error ?? Error_Error()}
    set {_error = newValue}
  }
  /// Returns true if `error` has been explicitly set.
  public var hasError: Bool {return self._error != nil}
  /// Clears the value of `error`. Subsequent reads from it will return its default value.
  public mutating func clearError() {self._error = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _error: Error_Error? = nil
}

public struct AccountBudget_GetAccountBudgetsRequest: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Токен доступа
  public var accessToken: String = String()

  /// Идентификаторы групп счетов (пусто - все доступные пользователю группы)
  public var accountGroupIds: [Data] = []

  /// Дата, от которой показывать версии бюджета
  public var dateFrom: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _dateFrom ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_dateFrom = newValue}
  }
  /// Returns true if `dateFrom` has been explicitly set.
  public var hasDateFrom: Bool {return self._dateFrom != nil}
  /// Clears the value of `dateFrom`. Subsequent reads from it will return its default value.
  public mutating func clearDateFrom() {self._dateFrom = nil}

  /// Дата, до которой показывать версии бюджета
  public var dateTo: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _dateTo ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_dateTo = newValue}
  }
  /// Returns true if `dateTo` has been explicitly set.
  public var hasDateTo: Bool {return self._dateTo != nil}
  /// Clears the value of `dateTo`. Subsequent reads from it will return its default value.
  public mutating func clearDateTo() {self._dateTo = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _dateFrom: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _dateTo: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

public struct AccountBudget_GetAccountBudgetsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Объект ошибки
  public var error: Error_Error {
    get {return _error ?? Error_Error()}
    set {_error = newValue}
  }
  /// Returns true if `error` has been explicitly set.
  public var hasError: Bool {return self._error != nil}
  /// Clears the value of `error`. Subsequent reads from it will return its default value.
  public mutating func clearError() {self._error = nil}

  /// Все версии бюджета по всем счетам запрошенных групп счетов
  public var budgets: [AccountBudget_AccountBudget] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _error: Error_Error? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "accountBudget"

extension AccountBudget_AccountBudget: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AccountBudget"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "accountID"),
    3: .same(proto: "amount"),
    4: .same(proto: "fixedSum"),
    5: .same(proto: "daysOffset"),
    6: .same(proto: "gradualFilling"),
    7: .same(proto: "effectiveFrom"),
    8: .same(proto: "createdByUserID"),
    9: .same(proto: "datetimeCreate"),
    10: .same(proto: "accountGroupID"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.accountID) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.amount) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self.fixedSum) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.daysOffset) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.gradualFilling) }()
      case 7: try { try decoder.decodeSingularMessageField(value: &self._effectiveFrom) }()
      case 8: try { try decoder.decodeSingularBytesField(value: &self.createdByUserID) }()
      case 9: try { try decoder.decodeSingularMessageField(value: &self._datetimeCreate) }()
      case 10: try { try decoder.decodeSingularBytesField(value: &self.accountGroupID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularBytesField(value: self.id, fieldNumber: 1)
    }
    if !self.accountID.isEmpty {
      try visitor.visitSingularBytesField(value: self.accountID, fieldNumber: 2)
    }
    if self.amount.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.amount, fieldNumber: 3)
    }
    if self.fixedSum.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.fixedSum, fieldNumber: 4)
    }
    if self.daysOffset != 0 {
      try visitor.visitSingularUInt32Field(value: self.daysOffset, fieldNumber: 5)
    }
    if self.gradualFilling != false {
      try visitor.visitSingularBoolField(value: self.gradualFilling, fieldNumber: 6)
    }
    try { if let v = self._effectiveFrom {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    } }()
    if !self.createdByUserID.isEmpty {
      try visitor.visitSingularBytesField(value: self.createdByUserID, fieldNumber: 8)
    }
    try { if let v = self._datetimeCreate {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    } }()
    if !self.accountGroupID.isEmpty {
      try visitor.visitSingularBytesField(value: self.accountGroupID, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: AccountBudget_AccountBudget, rhs: AccountBudget_AccountBudget) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.accountID != rhs.accountID {return false}
    if lhs.amount != rhs.amount {return false}
    if lhs.fixedSum != rhs.fixedSum {return false}
    if lhs.daysOffset != rhs.daysOffset {return false}
    if lhs.gradualFilling != rhs.gradualFilling {return false}
    if lhs._effectiveFrom != rhs._effectiveFrom {return false}
    if lhs.createdByUserID != rhs.createdByUserID {return false}
    if lhs._datetimeCreate != rhs._datetimeCreate {return false}
    if lhs.accountGroupID != rhs.accountGroupID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension AccountBudget_CreateAccountBudgetRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CreateAccountBudgetRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "accessToken"),
    2: .same(proto: "id"),
    3: .same(proto: "accountID"),
    4: .same(proto: "amount"),
    5: .same(proto: "fixedSum"),
    6: .same(proto: "daysOffset"),
    7: .same(proto: "gradualFilling"),
    8: .same(proto: "effectiveFrom"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.accessToken) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.id) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.accountID) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self.amount) }()
      case 5: try { try decoder.decodeSingularDoubleField(value: &self.fixedSum) }()
      case 6: try { try decoder.decodeSingularUInt32Field(value: &self.daysOffset) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self.gradualFilling) }()
      case 8: try { try decoder.decodeSingularMessageField(value: &self._effectiveFrom) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.accessToken.isEmpty {
      try visitor.visitSingularStringField(value: self.accessToken, fieldNumber: 1)
    }
    if !self.id.isEmpty {
      try visitor.visitSingularBytesField(value: self.id, fieldNumber: 2)
    }
    if !self.accountID.isEmpty {
      try visitor.visitSingularBytesField(value: self.accountID, fieldNumber: 3)
    }
    if self.amount.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.amount, fieldNumber: 4)
    }
    if self.fixedSum.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.fixedSum, fieldNumber: 5)
    }
    if self.daysOffset != 0 {
      try visitor.visitSingularUInt32Field(value: self.daysOffset, fieldNumber: 6)
    }
    if self.gradualFilling != false {
      try visitor.visitSingularBoolField(value: self.gradualFilling, fieldNumber: 7)
    }
    try { if let v = self._effectiveFrom {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: AccountBudget_CreateAccountBudgetRequest, rhs: AccountBudget_CreateAccountBudgetRequest) -> Bool {
    if lhs.accessToken != rhs.accessToken {return false}
    if lhs.id != rhs.id {return false}
    if lhs.accountID != rhs.accountID {return false}
    if lhs.amount != rhs.amount {return false}
    if lhs.fixedSum != rhs.fixedSum {return false}
    if lhs.daysOffset != rhs.daysOffset {return false}
    if lhs.gradualFilling != rhs.gradualFilling {return false}
    if lhs._effectiveFrom != rhs._effectiveFrom {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension AccountBudget_CreateAccountBudgetResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CreateAccountBudgetResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "error"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._error) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._error {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: AccountBudget_CreateAccountBudgetResponse, rhs: AccountBudget_CreateAccountBudgetResponse) -> Bool {
    if lhs._error != rhs._error {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension AccountBudget_GetAccountBudgetsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetAccountBudgetsRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "accessToken"),
    2: .same(proto: "accountGroupIDs"),
    3: .same(proto: "dateFrom"),
    4: .same(proto: "dateTo"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.accessToken) }()
      case 2: try { try decoder.decodeRepeatedBytesField(value: &self.accountGroupIds) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._dateFrom) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._dateTo) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.accessToken.isEmpty {
      try visitor.visitSingularStringField(value: self.accessToken, fieldNumber: 1)
    }
    if !self.accountGroupIds.isEmpty {
      try visitor.visitRepeatedBytesField(value: self.accountGroupIds, fieldNumber: 2)
    }
    try { if let v = self._dateFrom {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._dateTo {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: AccountBudget_GetAccountBudgetsRequest, rhs: AccountBudget_GetAccountBudgetsRequest) -> Bool {
    if lhs.accessToken != rhs.accessToken {return false}
    if lhs.accountGroupIds != rhs.accountGroupIds {return false}
    if lhs._dateFrom != rhs._dateFrom {return false}
    if lhs._dateTo != rhs._dateTo {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension AccountBudget_GetAccountBudgetsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetAccountBudgetsResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "error"),
    2: .same(proto: "budgets"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._error) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.budgets) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._error {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.budgets.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.budgets, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: AccountBudget_GetAccountBudgetsResponse, rhs: AccountBudget_GetAccountBudgetsResponse) -> Bool {
    if lhs._error != rhs._error {return false}
    if lhs.budgets != rhs.budgets {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
